spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # change this to your own jdbc url
    username: zzh  # change this to your own username (avoid using a superuser)
    password: 2580  # change this to your own password

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: info
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
