spring:
  datasource:
    # TODO: change the following to your own database configuration
    url:   jdbc:postgresql://localhost:5432/sustec
    username:   zzh
    password:   2580

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: info
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
